### ISSUE TITLE
templateUrl vs template

### ISSUE THREAD

**Issue by ShakedGold** [arcadeJHS/AngularVueIntegration#2]
in the integration of an angular component inside a vue component, you said that it is better to use templateUrl than use template, how do I use that in the code?

Do I just pass it in to $compile with no changes like: `$compile(this.component.templateUrl)(scope)`

Or get the html dynamically and pass it as a string like: `$compile(importedHtmlFromUrl)(scope)`

**Comment by arcadeJHS** [comment]
Basically I was saying what exemplified here: [/code/angularApp/components/innerDetail.js](https://github.com/arcadeJHS/AngularVueIntegration/blob/2e0f2ca5802f5e13bdbc116a702a42169052e993/code/angularApp/components/innerDetail.js).

```javascript
(function () {
	'use strict';

	angular.module('AngularApp').component('innerDetail', {
		templateUrl: 'angularApp/components/innerDetail.html',
		bindings: {
			innerData: '<'
		},
		controller: [function () {

			angular.extend(this, {
				title: 'The wise man say'
			});

		}]
	});

})();
```

Inside your angular component definition it's better to link and external template than to inline a html string.
